// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AutomationAndTestExperiment_CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIMyFormWindow UIMyFormWindow
        {
            get
            {
                if ((this.mUIMyFormWindow == null))
                {
                    this.mUIMyFormWindow = new UIMyFormWindow();
                }
                return this.mUIMyFormWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMyFormWindow mUIMyFormWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMyFormWindow : WinWindow
    {
        
        public UIMyFormWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MyForm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyForm");
            #endregion
        }
        
        #region Properties
        public UIMyStaticClassSayHiWindow UIMyStaticClassSayHiWindow
        {
            get
            {
                if ((this.mUIMyStaticClassSayHiWindow == null))
                {
                    this.mUIMyStaticClassSayHiWindow = new UIMyStaticClassSayHiWindow(this);
                }
                return this.mUIMyStaticClassSayHiWindow;
            }
        }
        
        public UIMessageDisplayWindow UIMessageDisplayWindow
        {
            get
            {
                if ((this.mUIMessageDisplayWindow == null))
                {
                    this.mUIMessageDisplayWindow = new UIMessageDisplayWindow(this);
                }
                return this.mUIMessageDisplayWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMyStaticClassSayHiWindow mUIMyStaticClassSayHiWindow;
        
        private UIMessageDisplayWindow mUIMessageDisplayWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMyStaticClassSayHiWindow : WinWindow
    {
        
        public UIMyStaticClassSayHiWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "MyStaticClass_SayHi_Btn";
            this.WindowTitles.Add("MyForm");
            #endregion
        }
        
        #region Properties
        public WinButton UIMyStaticClassSayHiButton
        {
            get
            {
                if ((this.mUIMyStaticClassSayHiButton == null))
                {
                    this.mUIMyStaticClassSayHiButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMyStaticClassSayHiButton.SearchProperties[WinButton.PropertyNames.Name] = "MyStaticClass.SayHi";
                    this.mUIMyStaticClassSayHiButton.WindowTitles.Add("MyForm");
                    #endregion
                }
                return this.mUIMyStaticClassSayHiButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMyStaticClassSayHiButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMessageDisplayWindow : WinWindow
    {
        
        public UIMessageDisplayWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "MessageDisplay";
            this.WindowTitles.Add("MyForm");
            #endregion
        }
        
        #region Properties
        public WinEdit UIMessageDisplayEdit
        {
            get
            {
                if ((this.mUIMessageDisplayEdit == null))
                {
                    this.mUIMessageDisplayEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIMessageDisplayEdit.SearchProperties[WinEdit.PropertyNames.Name] = "MessageDisplay";
                    this.mUIMessageDisplayEdit.WindowTitles.Add("MyForm");
                    #endregion
                }
                return this.mUIMessageDisplayEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIMessageDisplayEdit;
        #endregion
    }
}
